type TIcon =
  | "arrowTopRightOnSquare"
  | "arrowUturnLeft"
  | "briefcase"
  | "bookmark"
  | "bookOpen"
  | "buildingOffice"
  | "calendar"
  | "calendarDays"
  | "cake"
  | "chatBubbleLeftRight"
  | "check"
  | "chevronLeft"
  | "chevronRight"
  | "cursorArrowRays"
  | "computerDesktop"
  | "documentDuplicate"
  | "envelope"
  | "exclamationCircle"
  | "home"
  | "informationCircle"
  | "listBullet"
  | "magnifiyingGlass"
  | "mapPin"
  | "noSymbol"
  | "pencil"
  | "phone"
  | "plus"
  | "select"
  | "star"
  | "user"
  | "userGroup"
  | "xMark";

export default TIcon;
